services:
  postgres:
    image: postgres:16-alpine
    container_name: rfid_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rfid_user
      POSTGRES_PASSWORD: rfid_pass
      POSTGRES_DB: rfid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
